[versions]
activityKtx = "1.12.3"
agp = "9.0.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
core = "3.5.4"
coreKtxVersion = "1.17.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinStdlib = "2.2.21"
kotlinStdlibVersion = "2.2.21"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
composeBom = "2026.01.01"
material = "1.13.0"
multidex = "2.0.1"
opencsv = "5.12.0"
opencsvVersion = "5.12.0"
poi = "5.5.1"
poiOoxml = "5.5.1"
poiOoxmlFull = "5.5.1"
poiOoxmlLite = "5.5.1"
poiOoxmlVersion = "5.5.1"
poiVersion = "5.5.1"
timber = "5.0.1"
constraintlayoutCore = "1.1.1"
cameraCore = "1.5.3"
cameraMlkitVision = "1.5.3"
camerax = "1.5.3"
mlkit-barcode-scanning = "17.3.0"
accompanistPermissions = "0.37.3"

[libraries]
camera-mlkit-vision = { group = "androidx.camera", name = "camera-mlkit-vision", version.ref = "cameraMlkitVision" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
mlkit-barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkit-barcode-scanning" }
#For the permission
accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1170 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
core = { module = "com.google.zxing:core", version.ref = "core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-stdlib-v190 = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlibVersion" }
material = { module = "com.google.android.material:material", version.ref = "material" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
opencsv-v5120 = { module = "com.opencsv:opencsv", version.ref = "opencsvVersion" }
poi = { module = "org.apache.poi:poi", version.ref = "poi" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poiOoxml" }
poi-ooxml-full = { module = "org.apache.poi:poi-ooxml-full", version.ref = "poiOoxmlFull" }
poi-ooxml-lite = { module = "org.apache.poi:poi-ooxml-lite", version.ref = "poiOoxmlLite" }
poi-ooxml-v523 = { module = "org.apache.poi:poi-ooxml", version.ref = "poiOoxmlVersion" }
poi-v523 = { module = "org.apache.poi:poi", version.ref = "poiVersion" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-constraintlayout-core = { group = "androidx.constraintlayout", name = "constraintlayout-core", version.ref = "constraintlayoutCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

